spring:
  application:
    name: crud-example-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql
    show-sql: true
server:
  port: 9001

